name: Build and test

on:
  push:
    branches: [ main, rewrite ]
  pull_request:
    branches: [ main, rewrite ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: swift-actions/setup-swift@v1
    - name: Swift version
      run: swift --version
    - name: Dependencies
      run: |
        brew unlink libmarpa > /dev/null 2>&1 || true
        brew tap hylo-lang/homebrew-tap
        brew install --HEAD libmarpa-val
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
